FROM golang:1.22-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev 








RUN addgroup -S mercari && adduser -S trainee -G mercari
RUN chown -R trainee:mercari /app
# RUN chown -R trainee:mercari /path/to/db


RUN go mod tidy




EXPOSE 9000

USER trainee

CMD ["go","run","app/main.go"]
